In [1]:
from UnivariateAllFunctions import univariate
## Reading the data from CSV file
dataset=univariate.importDataset()

In [2]:
## Splitting the qual, quan data 
quan,qual = univariate.quanQual(dataset)

In [3]:
## Calling this function to retrieve univariate data's
descriptive=univariate.findUnivariate(dataset,quan)

In [4]:
## Calling this function to find the list of columns conting lower and higher outlier
lower,higher=univariate.checkforOutliers(descriptive,quan)
print(lower)
print(higher)

['hsc_p']
['hsc_p', 'degree_p', 'salary']

In [5]:
## Calling this function to set/replace the dataset with lowerIQR and higherIQR for the Outliers
descriptive=univariate.replaceOutliersWithIQRValues(dataset,descriptive,lower,higher)

In [6]:
## Rerunning this function to retrieve univariate data's after clean up
descriptive=univariate.findUnivariate(dataset,quan)

In [7]:
## Rerunning this function to check for outliers again. 
## Note: this should return an empty lower and higher list 
# as the clean up is done in earlier step
lower,higher=univariate.checkforOutliers(descriptive,quan)
print(lower)
print(higher)

[]
[]

In [8]:
## Calling this function to get the frequency Table for the input Column
freqTable=univariate.freqTable(dataset,"ssc_p")

In [9]:
## printing the frequency Table for verification
## commenting the table for now
## freqTable

In [10]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
LowerIQR,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
HigherIQR,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1.0,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
kurtosis,-1.091536,4.831444,4.872039,4.987453,4.41463,5.549355,-0.198676
skewVar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Std,77.182496,60.155559,60.18015,60.074509,59.029451,60.540676,129347.825756
skew,0.069716,1.911858,1.929387,1.905064,1.781288,2.064549,-0.706253
Var,5957.137619,3618.691225,3621.650503,3608.946583,3484.476044,3665.173443,16730860027.806198

In [11]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
LowerIQR,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
HigherIQR,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1.0,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
kurtosis,-1.091536,4.831444,4.872039,4.987453,4.41463,5.549355,-0.198676
skewVar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Std,77.182496,60.155559,60.18015,60.074509,59.029451,60.540676,129347.825756
skew,0.069716,1.911858,1.929387,1.905064,1.781288,2.064549,-0.706253
Var,5957.137619,3618.691225,3621.650503,3608.946583,3484.476044,3665.173443,16730860027.806198